"""initial schema

Revision ID: 0145807587fa
Revises: 
Create Date: 2025-05-07 18:59:43.052885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0145807587fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backlog_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('go_item', sa.String(length=20), nullable=False),
    sa.Column('item_number', sa.String(length=10), nullable=True),
    sa.Column('discrete', sa.String(length=50), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('import_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('go_item', sa.String(length=30), nullable=False),
    sa.Column('oracle', sa.String(length=10), nullable=True),
    sa.Column('item_number', sa.String(length=10), nullable=True),
    sa.Column('discrete_job', sa.String(length=50), nullable=True),
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('qty_req', sa.Integer(), nullable=False),
    sa.Column('amo_qty', sa.Integer(), nullable=True),
    sa.Column('surplus_qty', sa.Integer(), nullable=True),
    sa.Column('kb_qty', sa.Integer(), nullable=True),
    sa.Column('flow_status', sa.String(length=30), nullable=True),
    sa.Column('redcon_status', sa.Integer(), nullable=True),
    sa.Column('pick_status', sa.String(length=15), nullable=True),
    sa.Column('qty_remaining', sa.Integer(), nullable=True),
    sa.Column('shipping_info', sa.String(length=60), nullable=True),
    sa.Column('last_import_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picklist_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('go_item', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rapport_id', sa.Integer(), nullable=False),
    sa.Column('printed_at', sa.DateTime(), nullable=False),
    sa.Column('reprint', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapport_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('go_item', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('lines_json', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rapport_log')
    op.drop_table('print_log')
    op.drop_table('picklist_log')
    op.drop_table('main_item')
    op.drop_table('backlog_item')
    # ### end Alembic commands ###
